trigger:
- master

resources:
- repo: self

variables:
  skipComponentGovernanceDetection: true

jobs:  
- job: Build
  displayName: Build
  pool: k8spooldemo16
  steps:
  - script: img login -u $(username) -p $(password)
    displayName: Login to ACR using img
  - script: |
      POD=$(curl k8s-poolprovider:8082/consistenthash?key=shashankbarsin/pipelines-javascript-docker | jq -r .Message)
      echo $POD
    displayName: Build and push to ACR using buildctl

