trigger:
- master

resources:
- repo: self

variables:
  skipComponentGovernanceDetection: true

jobs:  
- job: Build
  displayName: Build
  pool: k8spooldemo16
  steps:
  - script: img login -u $(username) -p $(password)
    displayName: Login to ACR using img
  - script: |
      pod=$(curl k8s-poolprovider:8082/consistenthash?key=shashankbarsin/pipelines-javascript-docker | jq -r .Message)
      export BUILDKIT_HOST="kube-pod://${pod}?namespace=azuredevops"
      buildctl build --frontend=dockerfile.v0 --local context=app --local dockerfile=app --output type=image,name=shasb.azurecr.io/hellothere,push=true
    displayName: Build and push to ACR using buildctl

